# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.gogo.protobuf.gogoproto import gogo_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2
from github.com.gogo.protobuf.protobuf.google.protobuf import timestamp_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_protobuf_dot_google_dot_protobuf_dot_timestamp__pb2
from github.com.crypto_bank.proto.exchange import exchange_pb2 as github_dot_com_dot_crypto__bank_dot_proto_dot_exchange_dot_exchange__pb2
from github.com.crypto_bank.proto.currency import currency_pb2 as github_dot_com_dot_crypto__bank_dot_proto_dot_currency_dot_currency__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order/order.proto',
  package='order',
  syntax='proto3',
  serialized_pb=_b('\n\x11order/order.proto\x12\x05order\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\x1a\x41github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto\x1a\x34github.com/crypto-bank/proto/exchange/exchange.proto\x1a\x34github.com/crypto-bank/proto/currency/currency.proto\"\x8a\x01\n\x05Order\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.order.Type\x12 \n\x06volume\x18\x02 \x01(\x0b\x32\x10.currency.Volume\x12\x1e\n\x04rate\x18\x03 \x01(\x0b\x32\x10.currency.Volume\x12$\n\x08\x65xchange\x18\x04 \x01(\x0e\x32\x12.exchange.Exchange\"b\n\x05Trade\x12\x12\n\x02id\x18\x01 \x01(\x03\x42\x06\xe2\xde\x1f\x02ID\x12\x1b\n\x05order\x18\x02 \x01(\x0b\x32\x0c.order.Order\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*0\n\x04Type\x12\x10\n\x03\x41SK\x10\x00\x1a\x07\x8a\x9d \x03\x41sk\x12\x10\n\x03\x42ID\x10\x01\x1a\x07\x8a\x9d \x03\x42id\x1a\x04\x88\xa3\x1e\x00\x42\x0c\xd0\xe2\x1e\x01\xc8\xe2\x1e\x01\xa8\xe2\x1e\x01\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,github_dot_com_dot_gogo_dot_protobuf_dot_protobuf_dot_google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,github_dot_com_dot_crypto__bank_dot_proto_dot_exchange_dot_exchange__pb2.DESCRIPTOR,github_dot_com_dot_crypto__bank_dot_proto_dot_currency_dot_currency__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='order.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ASK', index=0, number=0,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \003Ask')),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BID', index=1, number=1,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \003Bid')),
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000')),
  serialized_start=491,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
ASK = 0
BID = 1



_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='order.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='order.Order.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='order.Order.volume', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='order.Order.rate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='order.Order.exchange', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=389,
)


_TRADE = _descriptor.Descriptor(
  name='Trade',
  full_name='order.Trade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.Trade.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\002ID'))),
    _descriptor.FieldDescriptor(
      name='order', full_name='order.Trade.order', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='order.Trade.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=489,
)

_ORDER.fields_by_name['type'].enum_type = _TYPE
_ORDER.fields_by_name['volume'].message_type = github_dot_com_dot_crypto__bank_dot_proto_dot_currency_dot_currency__pb2._VOLUME
_ORDER.fields_by_name['rate'].message_type = github_dot_com_dot_crypto__bank_dot_proto_dot_currency_dot_currency__pb2._VOLUME
_ORDER.fields_by_name['exchange'].enum_type = github_dot_com_dot_crypto__bank_dot_proto_dot_exchange_dot_exchange__pb2._EXCHANGE
_TRADE.fields_by_name['order'].message_type = _ORDER
_TRADE.fields_by_name['time'].message_type = github_dot_com_dot_gogo_dot_protobuf_dot_protobuf_dot_google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['Trade'] = _TRADE
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'order.order_pb2'
  # @@protoc_insertion_point(class_scope:order.Order)
  ))
_sym_db.RegisterMessage(Order)

Trade = _reflection.GeneratedProtocolMessageType('Trade', (_message.Message,), dict(
  DESCRIPTOR = _TRADE,
  __module__ = 'order.order_pb2'
  # @@protoc_insertion_point(class_scope:order.Trade)
  ))
_sym_db.RegisterMessage(Trade)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\320\342\036\001\310\342\036\001\250\342\036\001'))
_TYPE.has_options = True
_TYPE._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000'))
_TYPE.values_by_name["ASK"].has_options = True
_TYPE.values_by_name["ASK"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \003Ask'))
_TYPE.values_by_name["BID"].has_options = True
_TYPE.values_by_name["BID"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \003Bid'))
_TRADE.fields_by_name['id'].has_options = True
_TRADE.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\002ID'))
# @@protoc_insertion_point(module_scope)
