# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency/currency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.gogo.protobuf.gogoproto import gogo_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency/currency.proto',
  package='currency',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x63urrency/currency.proto\x12\x08\x63urrency\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\"\x1a\n\x08\x43urrency\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"M\n\x04Pair\x12!\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x12.currency.Currency\x12\"\n\x06second\x18\x02 \x01(\x0b\x32\x12.currency.Currency\">\n\x06Volume\x12$\n\x08\x63urrency\x18\x01 \x01(\x0b\x32\x12.currency.Currency\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x42\x0c\xd0\xe2\x1e\x01\xc8\xe2\x1e\x01\xa8\xe2\x1e\x01\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CURRENCY = _descriptor.Descriptor(
  name='Currency',
  full_name='currency.Currency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='currency.Currency.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=110,
)


_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='currency.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='currency.Pair.first', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='currency.Pair.second', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=189,
)


_VOLUME = _descriptor.Descriptor(
  name='Volume',
  full_name='currency.Volume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='currency.Volume.currency', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='currency.Volume.amount', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=253,
)

_PAIR.fields_by_name['first'].message_type = _CURRENCY
_PAIR.fields_by_name['second'].message_type = _CURRENCY
_VOLUME.fields_by_name['currency'].message_type = _CURRENCY
DESCRIPTOR.message_types_by_name['Currency'] = _CURRENCY
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['Volume'] = _VOLUME

Currency = _reflection.GeneratedProtocolMessageType('Currency', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCY,
  __module__ = 'currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:currency.Currency)
  ))
_sym_db.RegisterMessage(Currency)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), dict(
  DESCRIPTOR = _PAIR,
  __module__ = 'currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:currency.Pair)
  ))
_sym_db.RegisterMessage(Pair)

Volume = _reflection.GeneratedProtocolMessageType('Volume', (_message.Message,), dict(
  DESCRIPTOR = _VOLUME,
  __module__ = 'currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:currency.Volume)
  ))
_sym_db.RegisterMessage(Volume)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\320\342\036\001\310\342\036\001\250\342\036\001'))
# @@protoc_insertion_point(module_scope)
