# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderbook/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.gogo.protobuf.gogoproto import gogo_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2
from github.com.crypto_bank.proto.order import order_pb2 as github_dot_com_dot_crypto__bank_dot_proto_dot_order_dot_order__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orderbook/event.proto',
  package='orderbook',
  syntax='proto3',
  serialized_pb=_b('\n\x15orderbook/event.proto\x12\torderbook\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\x1a.github.com/crypto-bank/proto/order/order.proto\"b\n\x05\x45vent\x12\x12\n\x02id\x18\x01 \x01(\x03\x42\x06\xe2\xde\x1f\x02ID\x12\x1d\n\x05order\x18\x02 \x01(\x0b\x32\x0c.order.OrderH\x00\x12\x1d\n\x05trade\x18\x03 \x01(\x0b\x32\x0c.order.TradeH\x00\x42\x07\n\x05\x65vent\"/\n\x0b\x42\x61tchEvents\x12 \n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.orderbook.EventB\x17Z\torderbook\xd0\xe2\x1e\x01\xc8\xe2\x1e\x01\xa8\xe2\x1e\x01\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,github_dot_com_dot_crypto__bank_dot_proto_dot_order_dot_order__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='orderbook.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orderbook.Event.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\002ID'))),
    _descriptor.FieldDescriptor(
      name='order', full_name='orderbook.Event.order', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trade', full_name='orderbook.Event.trade', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='orderbook.Event.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=131,
  serialized_end=229,
)


_BATCHEVENTS = _descriptor.Descriptor(
  name='BatchEvents',
  full_name='orderbook.BatchEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='orderbook.BatchEvents.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=278,
)

_EVENT.fields_by_name['order'].message_type = github_dot_com_dot_crypto__bank_dot_proto_dot_order_dot_order__pb2._ORDER
_EVENT.fields_by_name['trade'].message_type = github_dot_com_dot_crypto__bank_dot_proto_dot_order_dot_order__pb2._TRADE
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['order'])
_EVENT.fields_by_name['order'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['trade'])
_EVENT.fields_by_name['trade'].containing_oneof = _EVENT.oneofs_by_name['event']
_BATCHEVENTS.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['BatchEvents'] = _BATCHEVENTS

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'orderbook.event_pb2'
  # @@protoc_insertion_point(class_scope:orderbook.Event)
  ))
_sym_db.RegisterMessage(Event)

BatchEvents = _reflection.GeneratedProtocolMessageType('BatchEvents', (_message.Message,), dict(
  DESCRIPTOR = _BATCHEVENTS,
  __module__ = 'orderbook.event_pb2'
  # @@protoc_insertion_point(class_scope:orderbook.BatchEvents)
  ))
_sym_db.RegisterMessage(BatchEvents)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\torderbook\320\342\036\001\310\342\036\001\250\342\036\001'))
_EVENT.fields_by_name['id'].has_options = True
_EVENT.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\002ID'))
# @@protoc_insertion_point(module_scope)
