# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities



class OrderBookStub(object):
  """Orders - Streams order book updates.
  rpc Orders(OrdersRequest) returns (stream OrderBookUpdate) {};
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class OrderBookServicer(object):
  """Orders - Streams order book updates.
  rpc Orders(OrdersRequest) returns (stream OrderBookUpdate) {};
  """


def add_OrderBookServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'orderbook.OrderBook', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
